// Shared data for ahmedabad.blog

window.AHM_DATA = {
  issue: { num: "Vol. 02 · Issue 14", date: "May 2026" },

  categories: [
    { slug: "cafes", name: "Cafés", count: 24, icon: "☕" },
    { slug: "coworking", name: "Coworking", count: 12, icon: "✦" },
    { slug: "gyms", name: "Gyms & Trainers", count: 18, icon: "✦" },
    { slug: "restaurants", name: "Restaurants", count: 42, icon: "✦" },
    { slug: "agencies", name: "Marketing Agencies", count: 16, icon: "✦" },
    { slug: "designers", name: "Interior Designers", count: 22, icon: "✦" },
    { slug: "doctors", name: "Doctors & Clinics", count: 31, icon: "✦" },
    { slug: "weekend", name: "Weekend Getaways", count: 14, icon: "✦" },
    { slug: "events", name: "Events This Month", count: 9, icon: "✦" },
  ],

  cafes: [
    {
      id: "amalgam",
      rank: "01",
      name: "Amalgam Coffee Roasters",
      neighborhood: "Navrangpura",
      featured: true,
      verified: true,
      pick: true,
      rating: 4.8,
      reviews: 412,
      price: 2,
      tags: ["Specialty Coffee", "Wi-Fi", "Brunch"],
      img: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=900&q=80",
      review: "If Ahmedabad has produced one café that can hold a candle to Bombay's third-wave scene, this is it. The owner — a former finance guy from Bodakdev — sources beans from Coorg and Chikmagalur and pulls one of the cleanest espressos in the state. Sit upstairs by the courtyard window.",
      pull: "the cleanest espresso in the state",
      hours: "7:00–22:00",
      phone: "+91 79 4002 1188",
      address: "Behind St. Xavier's, Navrangpura",
    },
    {
      id: "mocha",
      rank: "02",
      name: "Mocha Mojo & Co.",
      neighborhood: "C.G. Road",
      featured: true,
      verified: true,
      pick: false,
      rating: 4.6,
      reviews: 1208,
      price: 2,
      tags: ["All-day", "Outdoor seating"],
      img: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=900&q=80",
      review: "A Bombay import that found its rhythm in Ahmedabad faster than anyone expected. The shakshuka is shockingly good and the playlists genuinely work. Tuesdays are quiet; weekends are war.",
      pull: "shockingly good shakshuka",
      hours: "8:00–23:30",
      phone: "+91 79 2656 4421",
      address: "Opp. Crossword, C.G. Road",
    },
    {
      id: "blackforest",
      rank: "03",
      name: "Blackforest Hideout",
      neighborhood: "Bodakdev",
      featured: true,
      verified: true,
      pick: false,
      rating: 4.5,
      reviews: 624,
      price: 3,
      tags: ["Patisserie", "Quiet"],
      img: "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=900&q=80",
      review: "The croissants take 72 hours and you can taste every one of them. The owner trained in Lyon and refuses to compromise on butter. A small room, ten tables, no laptops after noon. A treasure.",
      pull: "no laptops after noon",
      hours: "8:00–20:00",
      phone: "+91 98257 33420",
      address: "Iscon Cross Roads, Bodakdev",
    },
    {
      id: "thirdwave",
      rank: "04",
      name: "Third Wave by the River",
      neighborhood: "Riverfront",
      featured: false,
      verified: true,
      pick: false,
      rating: 4.4,
      reviews: 388,
      price: 2,
      tags: ["Outdoor", "View"],
      img: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=900&q=80",
      review: "The Sabarmati view from the upper deck is the best in the city. Coffee is solid, food is forgettable, but you don't come here for either — you come to watch the sun fall behind the Mahatma's old footbridge.",
      pull: "best Sabarmati view in the city",
      hours: "6:30–22:00",
      phone: "+91 79 4990 1100",
      address: "Riverfront East, near Ellis Bridge",
    },
    {
      id: "kothi",
      rank: "05",
      name: "The Old Kothi",
      neighborhood: "Khadia (Old City)",
      featured: false,
      verified: true,
      pick: true,
      rating: 4.7,
      reviews: 286,
      price: 1,
      tags: ["Heritage", "Filter coffee"],
      img: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&q=80",
      review: "Set inside a 140-year-old pol house, restored by a young architect who returned from Berlin. They serve only filter coffee, masala chai, and one daily snack. The carved wooden ceiling alone is worth the trip into the old city.",
      pull: "the carved wooden ceiling alone is worth the trip",
      hours: "8:00–19:00",
      phone: "+91 98985 22113",
      address: "Doshiwada ni Pol, Khadia",
    },
    {
      id: "library",
      rank: "06",
      name: "Library Coffee House",
      neighborhood: "University Area",
      featured: false,
      verified: false,
      pick: false,
      rating: 4.3,
      reviews: 521,
      price: 1,
      tags: ["Books", "Study"],
      img: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=900&q=80",
      review: "Eight thousand books, two thousand of them readable, a hundred of them rare. CEPT and IIM kids treat it like an extension of the library, which is exactly the point. Coffee is fine; the atmosphere does the rest.",
      pull: "an extension of the library",
      hours: "9:00–23:00",
      phone: "+91 79 2630 2845",
      address: "Near CEPT, University Area",
    },
  ],

  // For the "Weekend Getaways" / "Events" / mixed homepage tease cards
  features: [
    {
      kind: "Editor's Letter",
      title: "What we mean by 'best'",
      excerpt: "We don't take money for rankings. We take money for visibility — Featured slots, sponsor strips, lead intros. The order is ours, and we'll defend it.",
      img: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=900&q=80",
    },
  ],
};
