import type { Category, Listing, CalendarEvent, IssueInfo } from './types'

export const issue: IssueInfo = { num: 'Vol. 02 · Issue 14', date: 'May 2026' }

export const categories: Category[] = [
  { slug: 'cafes', name: 'Cafés', count: 6, icon: '☕' },
  { slug: 'restaurants', name: 'Restaurants', count: 6, icon: '✦' },
  { slug: 'coworking', name: 'Coworking', count: 5, icon: '✦' },
  { slug: 'gyms', name: 'Gyms & Trainers', count: 5, icon: '✦' },
  { slug: 'agencies', name: 'Marketing Agencies', count: 5, icon: '✦' },
  { slug: 'designers', name: 'Interior Designers', count: 5, icon: '✦' },
  { slug: 'doctors', name: 'Doctors & Clinics', count: 5, icon: '✦' },
  { slug: 'weekend', name: 'Weekend Getaways', count: 6, icon: '✦' },
  { slug: 'events', name: 'Events This Month', count: 5, icon: '✦' },
]

// ─────────────────────────────────────────
// CAFÉS
// ─────────────────────────────────────────
export const cafes: Listing[] = [
  {
    id: 'amalgam',
    rank: '01',
    name: 'Amalgam Coffee Roasters',
    neighborhood: 'Navrangpura',
    featured: true,
    verified: true,
    pick: true,
    rating: 4.8,
    reviews: 412,
    price: 2,
    tags: ['Specialty Coffee', 'Wi-Fi', 'Brunch'],
    img: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=900&q=80',
    categorySlug: 'cafes',
    subtitle: 'Specialty roastery',
    review:
      "If Ahmedabad has produced one café that can hold a candle to Bombay's third-wave scene, this is it. The owner — a former finance guy from Bodakdev — sources beans from Coorg and Chikmagalur and pulls one of the cleanest espressos in the state. Sit upstairs by the courtyard window.",
    pull: 'the cleanest espresso in the state',
    quote:
      'He pulls a 1:2 ratio at 92°C, talks about extraction yields without sounding insufferable, and the result is in the cup.',
    body: [
      "Coffee in Ahmedabad has been a slow-build story. For most of the 2010s, the city's idea of a café was a milky cappuccino at CCD and a pastry that had been sitting under a glass dome since the previous Tuesday. Then came a few homegrown shops that took the work seriously. Amalgam is the most serious of them.",
      "The owner, Karan, spent eight years in finance before deciding he'd rather own a roastery. He sources from a single estate in Coorg and a couple of small farms outside Chikmagalur, roasts on a small Probat in the back, and — crucially — pays attention to the espresso machine. The food menu is short by design. The croissant is from Blackforest down the road. The ragi pancakes are surprisingly excellent. Don't order the salads.",
      'Sit upstairs. There\'s a window seat that looks out onto the courtyard, and it\'s the best chair in any café in this city.',
    ],
    attribution: '— Riya Shah · Visited Mar 2026 & Apr 2026',
    hours: '7:00–22:00',
    phone: '+91 79 4002 1188',
    address: "Behind St. Xavier's, Navrangpura",
    details: { 'Wi-Fi': 'Yes — fast', Seating: '42 inside · 12 courtyard', Parking: '2-wheeler only' },
    scores: { coffee: 4.9, atmosphere: 4.7, service: 4.6, value: 4.5 },
  },
  {
    id: 'mocha',
    rank: '02',
    name: 'Mocha Mojo & Co.',
    neighborhood: 'C.G. Road',
    featured: true,
    verified: true,
    pick: false,
    rating: 4.6,
    reviews: 1208,
    price: 2,
    tags: ['All-day', 'Outdoor seating'],
    img: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=900&q=80',
    categorySlug: 'cafes',
    subtitle: 'All-day café',
    review:
      "A Bombay import that found its rhythm in Ahmedabad faster than anyone expected. The shakshuka is shockingly good and the playlists genuinely work. Tuesdays are quiet; weekends are war.",
    pull: 'shockingly good shakshuka',
    body: [
      "It took them about six months to figure out Ahmedabad. The first iteration was too Bombay — too loud, too expensive, too confident. They recalibrated, trimmed the menu, and opened an outdoor section that now fills every evening from October to March.",
      "The coffee is consistent without being exceptional. What keeps people coming back is the atmosphere — the kind of casual, unhurried ease that most cafés in this city try to manufacture but can't. Here it just happens.",
    ],
    attribution: '— Dev Patel · Visited Feb 2026 & Apr 2026',
    hours: '8:00–23:30',
    phone: '+91 79 2656 4421',
    address: 'Opp. Crossword, C.G. Road',
    details: { 'Wi-Fi': 'Yes', Seating: '65 inside · 30 outdoor', Parking: 'Street parking available' },
    scores: { coffee: 4.5, atmosphere: 4.8, service: 4.4, value: 4.6 },
  },
  {
    id: 'blackforest',
    rank: '03',
    name: 'Blackforest Hideout',
    neighborhood: 'Bodakdev',
    featured: true,
    verified: true,
    pick: false,
    rating: 4.5,
    reviews: 624,
    price: 3,
    tags: ['Patisserie', 'Quiet'],
    img: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=900&q=80',
    categorySlug: 'cafes',
    subtitle: 'French patisserie',
    review:
      'The croissants take 72 hours and you can taste every one of them. The owner trained in Lyon and refuses to compromise on butter. A small room, ten tables, no laptops after noon. A treasure.',
    pull: 'no laptops after noon',
    body: [
      "Yash Thakkar came back from Lyon with a sourdough starter, three kilos of French butter, and an unusually strong opinion about lamination. His croissants are, by some margin, the best in Gujarat. The pain au chocolat is better.",
      "The no-laptops rule is posted on a small brass plate near the door. Some people are annoyed. Most, once they sit down with a pastry and an espresso, understand. This is a place built for eating, not working.",
    ],
    attribution: '— Riya Shah · Visited Jan 2026 & Mar 2026',
    hours: '8:00–20:00',
    phone: '+91 98257 33420',
    address: 'Iscon Cross Roads, Bodakdev',
    details: { 'Wi-Fi': 'No (by design)', Seating: '10 tables only', Parking: 'Basement available' },
    scores: { coffee: 4.4, atmosphere: 4.9, service: 4.3, value: 4.2 },
  },
  {
    id: 'thirdwave',
    rank: '04',
    name: 'Third Wave by the River',
    neighborhood: 'Riverfront',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.4,
    reviews: 388,
    price: 2,
    tags: ['Outdoor', 'View'],
    img: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=900&q=80',
    categorySlug: 'cafes',
    subtitle: 'Riverside café',
    review:
      "The Sabarmati view from the upper deck is the best in the city. Coffee is solid, food is forgettable, but you don't come here for either — you come to watch the sun fall behind the Mahatma's old footbridge.",
    pull: 'best Sabarmati view in the city',
    body: [
      "Opened in 2023 as part of the riverfront development, it has the one thing no other café in Ahmedabad can buy: a front-row seat to the river at golden hour. The upper deck fills by 5:30pm and doesn't clear until dark.",
      "The coffee is fine. The cold brew is better than expected. The food — sandwiches, pasta, the usual — is forgettable. None of that matters when the light turns the water to copper. Come for the view, order the cold brew.",
    ],
    attribution: '— Ananya Mehta · Visited Mar 2026',
    hours: '6:30–22:00',
    phone: '+91 79 4990 1100',
    address: 'Riverfront East, near Ellis Bridge',
    details: { 'Wi-Fi': 'Yes', Seating: '40 indoor · 80 deck', Parking: 'Riverfront lot' },
    scores: { coffee: 4.2, atmosphere: 4.8, service: 4.3, value: 4.4 },
  },
  {
    id: 'kothi',
    rank: '05',
    name: 'The Old Kothi',
    neighborhood: 'Khadia (Old City)',
    featured: false,
    verified: true,
    pick: true,
    rating: 4.7,
    reviews: 286,
    price: 1,
    tags: ['Heritage', 'Filter coffee'],
    img: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&q=80',
    categorySlug: 'cafes',
    subtitle: 'Heritage café',
    review:
      'Set inside a 140-year-old pol house, restored by a young architect who returned from Berlin. They serve only filter coffee, masala chai, and one daily snack. The carved wooden ceiling alone is worth the trip into the old city.',
    pull: 'the carved wooden ceiling alone is worth the trip',
    body: [
      "Nikhil Shah spent four years at a firm in Berlin before coming back to his family's pol house in Khadia. He did the restoration himself — mostly — stripping back forty years of paint and concrete to find the original carved teak underneath. The menu is deliberately minimal: filter coffee from Coorg, masala chai, and whatever his mother has made that morning.",
      "The neighbourhood itself is half the reason to come. Khadia's pols are among the finest examples of traditional urban planning anywhere in India — narrow lanes, shared stoops, carved doorways. The Old Kothi sits at the heart of one of the best-preserved stretches. Take a walk before you sit down.",
    ],
    attribution: '— Riya Shah · Visited Feb 2026',
    hours: '8:00–19:00',
    phone: '+91 98985 22113',
    address: 'Doshiwada ni Pol, Khadia',
    details: { 'Wi-Fi': 'No', Seating: '18 inside', Parking: 'Walk-in only' },
    scores: { coffee: 4.6, atmosphere: 5.0, service: 4.5, value: 4.9 },
  },
  {
    id: 'library',
    rank: '06',
    name: 'Library Coffee House',
    neighborhood: 'University Area',
    featured: false,
    verified: false,
    pick: false,
    rating: 4.3,
    reviews: 521,
    price: 1,
    tags: ['Books', 'Study'],
    img: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=900&q=80',
    categorySlug: 'cafes',
    subtitle: 'Bookshop café',
    review:
      'Eight thousand books, two thousand of them readable, a hundred of them rare. CEPT and IIM kids treat it like an extension of the library, which is exactly the point. Coffee is fine; the atmosphere does the rest.',
    pull: 'an extension of the library',
    body: [
      "There's a first-edition Gujarati translation of Tagore somewhere on the third shelf from the left. The owner will let you read it if you ask. He will not let you buy it.",
      "The coffee is not the reason to come, but it's better than average — a decent South Indian filter and a reasonable pour-over. Come for the books, stay for the quiet, leave having read something you didn't expect to.",
    ],
    attribution: '— Dev Patel · Visited Apr 2026',
    hours: '9:00–23:00',
    phone: '+91 79 2630 2845',
    address: 'Near CEPT, University Area',
    details: { 'Wi-Fi': 'Yes', Seating: '50 + reading alcoves', Parking: 'CEPT road parking' },
    scores: { coffee: 4.0, atmosphere: 4.6, service: 4.2, value: 4.5 },
  },
]

// ─────────────────────────────────────────
// RESTAURANTS
// ─────────────────────────────────────────
export const restaurants: Listing[] = [
  {
    id: 'haveli-rasoi',
    rank: '01',
    name: 'Haveli Rasoi',
    neighborhood: 'Khadia (Old City)',
    featured: true,
    verified: true,
    pick: true,
    rating: 4.9,
    reviews: 2104,
    price: 2,
    tags: ['Gujarati thali', 'Heritage', 'Dinner only'],
    img: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=900&q=80',
    categorySlug: 'restaurants',
    subtitle: 'Heritage dining',
    review:
      "Set inside a 200-year-old haveli in the old city, Haveli Rasoi serves the finest traditional Gujarati thali in Ahmedabad. The rotli is hand-rolled to order. The dal dhokli has been the same recipe for three generations. Nothing is written down.",
    pull: 'the finest traditional Gujarati thali in Ahmedabad',
    quote:
      'Twenty-two small bowls arrive at once, and the runner begins refilling before you have finished the first. This is hospitality as architecture.',
    body: [
      "The Mehta family has been running this haveli as a dining room since 1974, but the building itself is older — the carved wooden facade on Doshiwada ni Pol is from the 1820s. Dinner is served at two seatings: 7pm and 9pm. Reservations are technically required; arriving without one usually works anyway if you look friendly.",
      "The thali changes with the season. In winter: undhiyu, bajra rotla, a thick methi dal. In summer: keri no ras, cold kadhi, thin bajri. The kitchen tracks the Gujarati calendar more closely than a temple. If you come in the month of Shravan, expect an entirely different menu — and no garlic, no onion.",
    ],
    attribution: '— Ananya Mehta · Visited Mar 2026 & Apr 2026',
    hours: '19:00–23:00',
    phone: '+91 79 2215 8844',
    address: 'Doshiwada ni Pol, Khadia',
    details: { Cuisine: 'Gujarati thali', Seating: '80 covers', Reservations: 'Recommended', 'Avg spend': '₹450 per head' },
    scores: { food: 5.0, ambiance: 4.9, service: 4.7, value: 4.6 },
  },
  {
    id: 'prems-bistro',
    rank: '02',
    name: "Prem's Bistro",
    neighborhood: 'Satellite',
    featured: true,
    verified: true,
    pick: false,
    rating: 4.6,
    reviews: 841,
    price: 3,
    tags: ['Modern Gujarati', 'Wine', 'Weekend brunch'],
    img: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80',
    categorySlug: 'restaurants',
    subtitle: 'Modern Gujarati',
    review:
      "Gujarati food, but not as your grandmother makes it. Prem Trivedi studied at the Culinary Institute of America and came back to Ahmedabad to reinterpret his mother's recipes with French technique and a Noma-era reverence for fermentation. The results are unexpected and very good.",
    pull: 'reinterpret his mother\'s recipes with French technique',
    body: [
      "The khakhra chaat is the dish people talk about — a deconstructed version of the roadside snack, plated with pomegranate foam and kokum gel. It sounds like a caricature of modern Indian cooking; it tastes like you've been eating khakhra wrong for your entire life.",
      "The wine list is short and seriously chosen, which is rare in Ahmedabad. The by-the-glass options include two natural wines from Maharashtra. Weekend brunch runs from 11am to 3pm and books up two weeks ahead in season.",
    ],
    attribution: '— Riya Shah · Visited Apr 2026',
    hours: '12:00–15:00, 19:00–23:00',
    phone: '+91 79 4015 2200',
    address: 'Shyamal Cross Roads, Satellite',
    details: { Cuisine: 'Contemporary Gujarati', Seating: '48 covers', Reservations: 'Required weekends', 'Avg spend': '₹1,200 per head' },
    scores: { food: 4.7, ambiance: 4.5, service: 4.6, value: 4.4 },
  },
  {
    id: 'manek-nights',
    rank: '03',
    name: 'Manek Chowk Nights',
    neighborhood: 'Old City',
    featured: false,
    verified: true,
    pick: true,
    rating: 4.7,
    reviews: 5821,
    price: 1,
    tags: ['Street food', 'Late night', 'Iconic'],
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900&q=80',
    categorySlug: 'restaurants',
    subtitle: 'Night food market',
    review:
      "By day a jewellery market. By night, the most democratic dining experience in India. After 9pm, Manek Chowk transforms into 200 metres of food stalls stretching from the old clock tower to the haveli wall. Come for the Jain pizza. Stay for the falooda.",
    pull: 'the most democratic dining experience in India',
    body: [
      "The stalls set up around 9:30pm and run until 2am, sometimes later. Most of them have been here for decades — the same families, the same recipes, the same prices (give or take inflation). The pav bhaji is cooked on a flat iron the size of a dining table. The sev puri counter moves so fast it looks choreographed.",
      "There is nothing chic about Manek Chowk and that is precisely the point. Everyone is here: the mill-owner family from Paldi, the CEPT students, the street vendor from Kalupur who finally has a night off. Eat standing up. Order in Gujarati if you can.",
    ],
    attribution: '— Ananya Mehta · Visited monthly',
    hours: '21:30–02:00',
    phone: 'No reservations',
    address: 'Manek Chowk, Khadia Gate, Old City',
    details: { Cuisine: 'Gujarati street food', Seating: 'Street standing', Reservations: 'Walk-in only', 'Avg spend': '₹120 per head' },
    scores: { food: 4.8, ambiance: 4.3, service: 4.1, value: 5.0 },
  },
  {
    id: 'grain-table',
    rank: '04',
    name: 'The Grain Table',
    neighborhood: 'SG Highway',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.4,
    reviews: 523,
    price: 3,
    tags: ['Farm-to-table', 'Organic', 'Vegetarian'],
    img: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80',
    categorySlug: 'restaurants',
    subtitle: 'Farm-to-table',
    review:
      "Every vegetable on the menu has a postcode. The Grain Table sources exclusively from farms within 200km of Ahmedabad — Anand's dairy, Sabarkantha's produce, Kutchi sesame — and the kitchen does very little to get in the way of that quality.",
    pull: 'every vegetable on the menu has a postcode',
    body: [
      "Chef Priti Desai moved back to Ahmedabad from a Michelin-starred kitchen in London with a clear idea: Gujarat is one of the world's great vegetarian pantries, and most restaurants treat it like a constraint rather than an advantage. The Grain Table is her correction.",
      "The tasting menu changes every two weeks. Recent dishes have included a 48-hour fermented bajra risotto, a cold kadhi with compressed cucumber, and a dessert of chaas sorbet with honey from Sabarkantha. Portions are small. The experience is not.",
    ],
    attribution: '— Riya Shah · Visited Mar 2026',
    hours: '12:30–15:00, 19:30–22:30',
    phone: '+91 98240 77612',
    address: 'Beside Iscon Mega Mall, SG Highway',
    details: { Cuisine: 'Contemporary vegetarian', Seating: '36 covers', Reservations: 'Essential', 'Avg spend': '₹1,800 per head' },
    scores: { food: 4.6, ambiance: 4.4, service: 4.5, value: 4.1 },
  },
  {
    id: 'kabirs-kitchen',
    rank: '05',
    name: "Kabir's Kitchen",
    neighborhood: 'Navrangpura',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.3,
    reviews: 671,
    price: 2,
    tags: ['Non-veg', 'Kebabs', 'Old-school'],
    img: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=900&q=80',
    categorySlug: 'restaurants',
    subtitle: 'North Indian non-veg',
    review:
      "The murgh malai tikka at Kabir's Kitchen is the best argument for non-veg in a proudly vegetarian city. The tandoor has been running since 1991. The owner, Kabir Hussain, still comes in at 6am to marinate the meat. The biryani takes four hours and it shows.",
    pull: 'the best argument for non-veg in a proudly vegetarian city',
    body: [
      "Kabir's is not easy to find — it's in a lane off Relief Road with no signage visible from the street, and the parking situation requires creative thinking. None of that stops it filling every night from 7pm onwards.",
      "Order the seekh kebab, the dal makhani, and if you're there on a Friday, the biryani. Skip the Chinese section entirely. The lassi is excellent. Cash only.",
    ],
    attribution: '— Dev Patel · Visited Feb 2026 & Apr 2026',
    hours: '12:00–15:30, 19:00–23:30',
    phone: '+91 79 2657 1122',
    address: 'Relief Road Lane 4, Navrangpura',
    details: { Cuisine: 'North Indian', Seating: '55 covers', Reservations: 'Walk-in', 'Avg spend': '₹600 per head' },
    scores: { food: 4.5, ambiance: 4.1, service: 4.2, value: 4.4 },
  },
  {
    id: 'dal-dhokla',
    rank: '06',
    name: 'Dal & Dhokla',
    neighborhood: 'Multiple locations',
    featured: false,
    verified: false,
    pick: false,
    rating: 4.2,
    reviews: 4820,
    price: 1,
    tags: ['Fast casual', 'Gujarati snacks', 'Budget'],
    img: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=900&q=80',
    categorySlug: 'restaurants',
    subtitle: 'Gujarati fast casual',
    review:
      "The best dhokla in the city, served at the speed of a chaiwalla. Dal & Dhokla has nine locations across Ahmedabad and the quality is consistent in a way that ought to be impossible for a fast-casual chain. The fafda-jalebi combo at breakfast is one of the great cheap meals in Gujarat.",
    pull: 'one of the great cheap meals in Gujarat',
    body: [
      "The Bodakdev branch is the original and still the best. The dhokla is steamed fresh every two hours. The khaman is softer than air. The green chutney is made from scratch each morning.",
      "Don't come here for the ambiance — the lighting is fluorescent and the seating is bench-style. Come here because ₹120 buys you a breakfast that will keep you going until dinner.",
    ],
    attribution: '— Ananya Mehta · Visited regularly',
    hours: '7:00–22:00',
    phone: '+91 79 2685 3300',
    address: 'Bodakdev, C.G. Road, Vastrapur & more',
    details: { Cuisine: 'Gujarati snacks', Seating: 'Bench seating', Reservations: 'Walk-in', 'Avg spend': '₹100–150 per head' },
    scores: { food: 4.4, ambiance: 3.8, service: 4.1, value: 4.9 },
  },
]

// ─────────────────────────────────────────
// COWORKING
// ─────────────────────────────────────────
export const coworking: Listing[] = [
  {
    id: 'the-loft',
    rank: '01',
    name: 'The Loft',
    neighborhood: 'SG Highway',
    featured: true,
    verified: true,
    pick: true,
    rating: 4.7,
    reviews: 312,
    price: 3,
    tags: ['Fibre internet', 'Private cabins', 'Standing desks'],
    img: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80',
    categorySlug: 'coworking',
    subtitle: 'Premium coworking',
    review:
      "The best internet connection in any coworking space we tested — 1 Gbps, symmetric, and it actually delivers. The Loft is what enterprise office design looks like when someone with taste runs the budget: standing desks, acoustic panels that work, and coffee that doesn't taste like a penalty.",
    pull: 'the best internet in any coworking space we tested',
    body: [
      "Eight private cabins, 60 hot desks, two boardrooms with proper video-conferencing gear. The ventilation system is silent. These seem like small things until you've spent a summer in a coworking space in Ahmedabad with cheap AC and a rattling air handler.",
      "The day pass is ₹600. The monthly hot desk is ₹7,500. For what you get, this is reasonable. The free espresso machine alone justifies half the premium.",
    ],
    attribution: '— Dev Patel · Tested Feb 2026',
    hours: '7:00–23:00',
    phone: '+91 79 4020 8866',
    address: 'Prahladnagar Corporate Road, SG Highway',
    details: { 'Day pass': '₹600', 'Monthly hot desk': '₹7,500', Cabins: '8 private', Internet: '1 Gbps fibre' },
    scores: { internet: 4.9, space: 4.7, amenities: 4.8, value: 4.3 },
  },
  {
    id: 'pol-house-studios',
    rank: '02',
    name: 'Pol House Studios',
    neighborhood: 'Khadia (Old City)',
    featured: false,
    verified: true,
    pick: true,
    rating: 4.6,
    reviews: 184,
    price: 2,
    tags: ['Heritage', 'Photography-friendly', 'Quiet'],
    img: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&q=80',
    categorySlug: 'coworking',
    subtitle: 'Heritage coworking',
    review:
      "A 180-year-old pol house converted into the most photogenic workspace in Gujarat. The carved teak screens cast long shadows in the afternoon. The internet is fast. The silence is extraordinary for a building this old in a neighbourhood this dense.",
    pull: 'the most photogenic workspace in Gujarat',
    body: [
      "Soham Rao bought the haveli in 2022 and spent two years restoring it, refusing to replace any original woodwork. The result is a working space that feels more like a museum than an office — except the coffee is better and nobody shushes you for typing.",
      "Thirty-two desks across three floors. No hot-desking: every member gets an assigned seat. Waiting list for membership is currently about six weeks. Worth it.",
    ],
    attribution: '— Riya Shah · Tested Mar 2026',
    hours: '8:00–21:00',
    phone: '+91 98250 44121',
    address: 'Near Teen Darwaza, Khadia',
    details: { 'Day pass': '₹400', 'Monthly desk': '₹5,500', Internet: '500 Mbps', 'Unique feature': 'Heritage building' },
    scores: { internet: 4.4, space: 4.9, amenities: 4.2, value: 4.7 },
  },
  {
    id: 'satellite-desk',
    rank: '03',
    name: 'Satellite Desk',
    neighborhood: 'Satellite',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.3,
    reviews: 521,
    price: 1,
    tags: ['Budget', '24/7 access', 'Parking'],
    img: 'https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?w=900&q=80',
    categorySlug: 'coworking',
    subtitle: 'Budget coworking',
    review:
      "No frills, no pretense, no barista. Satellite Desk is the honest answer to a simple question: where can I get a desk, reliable internet, and a power socket at 2am? The 24/7 access and generous parking make it the only real option for night-owl freelancers west of Vastrapur.",
    pull: 'the honest answer to a simple question',
    body: [
      "The design is nothing. Fluorescent lights, modular desks, a coffee vending machine that gets the job done. But the internet has never once gone down in six months of testing, the AC runs through the night, and the ₹3,500 monthly rate is hard to argue with.",
      "If you need to look impressive on a client call, go elsewhere. If you need to ship code at 11pm, Satellite Desk is your place.",
    ],
    attribution: '— Dev Patel · Tested Jan 2026',
    hours: '24 hours, 7 days',
    phone: '+91 79 4018 9900',
    address: 'Shreyas Colony, Satellite',
    details: { 'Day pass': '₹250', 'Monthly hot desk': '₹3,500', Internet: '400 Mbps', Access: '24/7' },
    scores: { internet: 4.6, space: 3.9, amenities: 3.8, value: 4.9 },
  },
  {
    id: 'flow-cowork',
    rank: '04',
    name: 'Flow',
    neighborhood: 'Bodakdev',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.5,
    reviews: 267,
    price: 2,
    tags: ['Yoga room', 'Meditation', 'Wellness'],
    img: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=900&q=80',
    categorySlug: 'coworking',
    subtitle: 'Wellness coworking',
    review:
      "The only coworking space in Ahmedabad with a 200 sq.ft meditation room, a standing bar with ergonomic mats, and a morning yoga class included in the monthly membership. Either you're the target audience or you're not.",
    pull: 'either you\'re the target audience or you\'re not',
    body: [
      "Flow launched in 2024 targeting remote workers who'd spent the pandemic discovering that their bodies needed more than a chair. The design is Bali-meets-Bodakdev: natural light, plants that are actually alive, warm-toned wood and rattan where other spaces use plastic.",
      "The yoga class runs Monday, Wednesday, Friday at 7am. The meditation room books up by 10am daily. The internet is solid. The community of members skews wellness-entrepreneurial, which means the conversations in the kitchen are either fascinating or exhausting depending on your mood.",
    ],
    attribution: '— Ananya Mehta · Tested Apr 2026',
    hours: '6:30–21:00',
    phone: '+91 79 4022 6611',
    address: 'Judges Bungalow Road, Bodakdev',
    details: { 'Day pass': '₹500', 'Monthly hot desk': '₹6,500', 'Yoga': 'Included 3×/week', Internet: '300 Mbps' },
    scores: { internet: 4.4, space: 4.6, amenities: 4.9, value: 4.3 },
  },
  {
    id: 'the-grid',
    rank: '05',
    name: 'The Grid',
    neighborhood: 'Chandkheda',
    featured: false,
    verified: false,
    pick: false,
    rating: 4.4,
    reviews: 198,
    price: 2,
    tags: ['Startups', 'Events', 'GIFT City proximity'],
    img: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=900&q=80',
    categorySlug: 'coworking',
    subtitle: 'Startup hub',
    review:
      "Built for founders, not freelancers. The Grid sits near GIFT City and draws a specific crowd — fintech operators, logistics startups, the occasional VC doing due diligence. The event programming is the best of any coworking space in the city.",
    pull: 'built for founders, not freelancers',
    body: [
      "The Grid hosts two or three events per week: founder mixers, pitch sessions, workshop afternoons with operators from Mumbai and Bangalore. The membership fee is partly a room rental, partly a community subscription.",
      "Infrastructure is solid. The internet is 600 Mbps with a backup line. Four large meeting rooms with video conferencing. The snack bar is uninspired but functional. For GIFT City-adjacent companies, this is the obvious choice.",
    ],
    attribution: '— Dev Patel · Tested Mar 2026',
    hours: '7:00–22:00',
    phone: '+91 79 4030 5522',
    address: 'GIFT City Road, Chandkheda',
    details: { 'Day pass': '₹450', 'Monthly hot desk': '₹6,000', Internet: '600 Mbps', Events: '2–3 per week' },
    scores: { internet: 4.8, space: 4.3, amenities: 4.5, value: 4.4 },
  },
]

// ─────────────────────────────────────────
// GYMS & TRAINERS
// ─────────────────────────────────────────
export const gyms: Listing[] = [
  {
    id: 'iron-meridian',
    rank: '01',
    name: 'Iron Meridian',
    neighborhood: 'Bodakdev',
    featured: true,
    verified: true,
    pick: true,
    rating: 4.8,
    reviews: 489,
    price: 3,
    tags: ['CrossFit', 'Olympic lifting', 'Small batches'],
    img: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=900&q=80',
    categorySlug: 'gyms',
    subtitle: 'Functional fitness',
    review:
      "The best coaching in Ahmedabad, and it's not particularly close. Iron Meridian runs batches of eight. Every session is programmed. Every coach has been trained to fix your form before adding weight. The equipment is Rogue, the flooring is horse stall mats, and the results are real.",
    pull: 'the best coaching in Ahmedabad, and it\'s not particularly close',
    body: [
      "Head coach Sameer Vohra has been competing in weightlifting since 2014. He doesn't train everyone — there's an entry assessment, and if your mobility is too restricted for Olympic lifts, he'll say so and send you somewhere that will actually help you. This kind of honesty is rare and worth paying for.",
      "Monthly membership at ₹4,500 includes unlimited sessions. The morning 6am batch is the competitive one. The 7pm batch is more mixed. Both are coached equally well.",
    ],
    attribution: '— Dev Patel · Member, 4 months',
    hours: '6:00–21:00',
    phone: '+91 98244 66123',
    address: 'Judges Bungalow Cross Roads, Bodakdev',
    details: { Monthly: '₹4,500', 'Batch size': '8 max', Equipment: 'Rogue', Showers: 'Yes — clean' },
    scores: { equipment: 4.9, coaching: 5.0, cleanliness: 4.7, value: 4.4 },
  },
  {
    id: 'the-studio-gym',
    rank: '02',
    name: 'The Studio',
    neighborhood: 'Navrangpura',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.6,
    reviews: 612,
    price: 3,
    tags: ['Pilates', 'Reformer', 'Women-led'],
    img: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=900&q=80',
    categorySlug: 'gyms',
    subtitle: 'Boutique fitness',
    review:
      "The first Pilates reformer studio in Ahmedabad, and still the best. The space is beautiful — white walls, high ceilings, Merrithew reformers in two rows of six. The instruction is precise. The waiting list for peak-hour classes has been running since the day it opened.",
    pull: 'the first Pilates reformer studio in Ahmedabad',
    body: [
      "Founder Nisha Kapoor trained in New York and brought back not just the reformers but a particular understanding of the method — which is to say, she actually knows what Pilates is supposed to do and why. Many studios don't.",
      "Classes run 45 minutes, maximum 10 people. Monthly membership: ₹5,500 for 12 sessions. The Saturday 9am class is impossible to book without a week's notice.",
    ],
    attribution: '— Riya Shah · Attended 6 classes',
    hours: '6:30–21:00',
    phone: '+91 79 2644 5566',
    address: 'Swastik Society, Navrangpura',
    details: { Monthly: '₹5,500 (12 sessions)', 'Batch size': '10 max', Equipment: 'Merrithew reformers', Showers: 'Yes' },
    scores: { equipment: 4.8, coaching: 4.7, cleanliness: 4.9, value: 4.2 },
  },
  {
    id: 'shyams-iron',
    rank: '03',
    name: "Shyam's Iron Palace",
    neighborhood: 'Bapunagar',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.4,
    reviews: 1204,
    price: 1,
    tags: ['Free weights', 'Old-school', 'Bodybuilding'],
    img: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=900&q=80',
    categorySlug: 'gyms',
    subtitle: 'Old-school gym',
    review:
      "Running since 1987. No EDM, no Instagram mirrors, no protein shake bar. Shyam's is the place serious lifters in Ahmedabad eventually find — a basement full of iron that has been moved by people who knew what they were doing. The legacy equipment is better maintained than most gyms' new gear.",
    pull: 'the place serious lifters in Ahmedabad eventually find',
    body: [
      "Shyam Prajapati opened this place with six barbells and a bench. He now has four benches, an Olympic platform, and a collection of free weights that would make most commercial gyms jealous. He is present every morning at 5:30am and leaves at 9pm. This is his life's work.",
      "Monthly membership: ₹1,200. If you're a student, ₹900. There is no contract. The clientele are mostly serious — serious enough that the atmosphere during peak hours has a focus that is almost meditative.",
    ],
    attribution: '— Dev Patel · Member, 2 years',
    hours: '5:30–21:30',
    phone: '+91 98985 11234',
    address: 'Near Raipur Chakla, Bapunagar',
    details: { Monthly: '₹1,200', Equipment: 'Free weights, Olympic bar', Showers: 'Basic', 'Est.': '1987' },
    scores: { equipment: 4.6, coaching: 4.3, cleanliness: 3.9, value: 4.9 },
  },
  {
    id: 'sattva-yoga',
    rank: '04',
    name: 'Sattva Yoga',
    neighborhood: 'Usmanpura',
    featured: false,
    verified: true,
    pick: true,
    rating: 4.7,
    reviews: 342,
    price: 2,
    tags: ['Ashtanga', 'Pranayama', 'Mysore-style'],
    img: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=900&q=80',
    categorySlug: 'gyms',
    subtitle: 'Yoga studio',
    review:
      "Run by a former CEPT professor who studied in Mysore for two years and came back with one idea: teach the traditional method, without modification. The Mysore-style morning practice starts at 6am. No music. No mirrors. No adjustments until you ask for them.",
    pull: 'teach the traditional method, without modification',
    body: [
      "Vikram Nair's studio is 800 sq.ft. of clean wood floor, good light, and nothing else. He teaches a maximum of 15 students per session. He is not warm in the way of many yoga teachers, but he is precise, and his adjustments — when they come — change things.",
      "New students start with a mandatory two-week assessment before joining the regular practice. This weeds out the casual browsers. What remains is a serious room that has produced several students who've gone on to study in Mysore themselves.",
    ],
    attribution: '— Ananya Mehta · 3-month practitioner',
    hours: '6:00–20:00',
    phone: '+91 98242 33411',
    address: 'Near Usmanpura Bridge, Usmanpura',
    details: { Monthly: '₹2,800', 'Style': 'Ashtanga Mysore', 'Batch size': '15 max', Showers: 'Yes' },
    scores: { equipment: 4.3, coaching: 4.9, cleanliness: 4.8, value: 4.6 },
  },
  {
    id: 'hiit-house',
    rank: '05',
    name: 'HIIT House',
    neighborhood: 'Satellite',
    featured: false,
    verified: false,
    pick: false,
    rating: 4.3,
    reviews: 721,
    price: 2,
    tags: ['HIIT', 'Group classes', '45-min sessions'],
    img: 'https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=900&q=80',
    categorySlug: 'gyms',
    subtitle: 'Group HIIT training',
    review:
      "45-minute sessions, 10 people maximum, no mercy. HIIT House is not a gym in the traditional sense — there are no machines, no mirrors, no membership tiers. Just a trainer, a playlist, and a progressively terrible next 45 minutes. Results show up in about three weeks.",
    pull: 'no mercy',
    body: [
      "The model is simple: pay per class (₹350) or buy a 20-class pack (₹5,500). Sessions are timetabled by intensity — beginner, intermediate, advanced. The advanced classes have been described by members as 'punishing in the best way.'",
      "The equipment is functional: battle ropes, kettlebells, sleds, plyometric boxes. The space is well-ventilated and the coaches rotate, which keeps the programming fresh. No frills. Works.",
    ],
    attribution: '— Riya Shah · 5 sessions attended',
    hours: '6:00–20:30',
    phone: '+91 79 4011 8844',
    address: 'Anand Nagar Road, Satellite',
    details: { 'Per class': '₹350', '20-class pack': '₹5,500', 'Batch size': '10 max', Showers: 'Yes' },
    scores: { equipment: 4.5, coaching: 4.4, cleanliness: 4.5, value: 4.3 },
  },
]

// ─────────────────────────────────────────
// MARKETING AGENCIES
// ─────────────────────────────────────────
export const agencies: Listing[] = [
  {
    id: 'kairos-digital',
    rank: '01',
    name: 'Kairos Digital',
    neighborhood: 'SG Highway',
    featured: true,
    verified: true,
    pick: true,
    rating: 4.8,
    reviews: 156,
    price: 3,
    tags: ['Google Ads', 'Meta Ads', 'ROI-focused'],
    img: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&q=80',
    categorySlug: 'agencies',
    subtitle: 'Performance marketing',
    review:
      "The only agency in Ahmedabad that will tell you when your budget is wrong — and they'll back it up with data. Kairos Digital has a standing rule: if they can't improve your ROAS in 90 days, they refund the management fee. In three years, they've refunded it twice.",
    pull: 'if they can\'t improve your ROAS in 90 days, they refund the management fee',
    body: [
      "Founders Karan Mehta and Shreya Joshi came out of performance marketing roles at a D2C startup in Bengaluru. They built Kairos around one metric — return on ad spend — and refuse to report on anything else. No vanity metrics. No reach reports. Revenue in, revenue out.",
      "Their client roster is skewed toward mid-size Gujarati manufacturers moving into D2C (textiles, FMCG, industrial equipment). Minimum engagement: ₹50,000/month in ad spend. Not cheap, but the results support the price.",
    ],
    attribution: '— Interviewed Apr 2026 + client references',
    hours: '9:30–18:30',
    phone: '+91 79 4025 3344',
    address: 'Prahlad Nagar, SG Highway',
    details: { 'Min. ad spend': '₹50,000/month', 'Management fee': '10–15% of spend', Speciality: 'D2C & manufacturing', Team: '12 people' },
    scores: { results: 4.9, communication: 4.7, speed: 4.6, value: 4.5 },
  },
  {
    id: 'the-storybox',
    rank: '02',
    name: 'The Storybox',
    neighborhood: 'Navrangpura',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.6,
    reviews: 89,
    price: 2,
    tags: ['Content', 'Instagram', 'Reels & video'],
    img: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=900&q=80',
    categorySlug: 'agencies',
    subtitle: 'Content & social',
    review:
      "Three ex-journalists who decided brand storytelling pays better. The Storybox doesn't do paid ads — they do the thing underneath: the brand voice, the editorial strategy, the content that makes paid ads worth running in the first place. For Ahmedabad's growing number of lifestyle brands, they're the obvious first call.",
    pull: 'the thing underneath',
    body: [
      "Priya Vora, Nikhil Shah, and Arun Desai left newsrooms in 2021 to start The Storybox. Their pitch is simple: most agencies produce content that looks like content. They produce content that looks like media. The difference shows in the engagement numbers.",
      "They work with 15 brands simultaneously, maximum. The waitlist is currently four months. Retainers start at ₹80,000/month for a comprehensive content programme.",
    ],
    attribution: '— Interviewed Mar 2026',
    hours: '10:00–19:00',
    phone: '+91 79 2644 8811',
    address: 'Swastik Society, Navrangpura',
    details: { 'Min. retainer': '₹80,000/month', Speciality: 'Content & brand voice', 'Max clients': '15', Team: '8 people' },
    scores: { results: 4.7, communication: 4.8, speed: 4.4, value: 4.6 },
  },
  {
    id: 'meridian-media',
    rank: '03',
    name: 'Meridian Media',
    neighborhood: 'Bodakdev',
    featured: true,
    verified: true,
    pick: false,
    rating: 4.4,
    reviews: 112,
    price: 3,
    tags: ['Full-service', 'Traditional + Digital', 'Large brands'],
    img: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=900&q=80',
    categorySlug: 'agencies',
    subtitle: 'Full-service agency',
    review:
      "The old guard, but sharper than you'd expect. Meridian Media has been running since 2009 and has survived the digital transition better than most agencies of its generation. They're the agency Ahmedabad's large industrial families trust with serious budgets — and they've earned that trust with consistent results.",
    pull: 'the old guard, but sharper than you\'d expect',
    body: [
      "In 2020, Meridian hired an entirely new digital team — not to merge with the traditional practice, but to run alongside it. The result is an agency that can do a print campaign, a TV spot, a Meta retargeting funnel, and a PR offensive simultaneously. Most Ahmedabad agencies can do one of those things well.",
      "Fee structure is traditional: project quotes and monthly retainers. Minimum engagement typically ₹2 lakh per month. They're not cheap and they're not always fast. They are reliable.",
    ],
    attribution: '— Interviewed Feb 2026',
    hours: '9:00–18:00',
    phone: '+91 79 2680 4400',
    address: 'Judges Bungalow Road, Bodakdev',
    details: { 'Min. retainer': '₹2,00,000/month', Speciality: 'Integrated traditional + digital', Founded: '2009', Team: '45 people' },
    scores: { results: 4.5, communication: 4.3, speed: 4.1, value: 4.2 },
  },
  {
    id: 'craft-convert',
    rank: '04',
    name: 'Craft & Convert',
    neighborhood: 'Satellite',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.5,
    reviews: 67,
    price: 2,
    tags: ['Email marketing', 'D2C', 'Shopify'],
    img: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=900&q=80',
    categorySlug: 'agencies',
    subtitle: 'Email & D2C growth',
    review:
      "Built specifically for Ahmedabad's booming D2C textile and fashion brands. Craft & Convert does one thing: take a Shopify store with good products and make it grow — through email, SMS, conversion rate optimisation, and retention systems. They don't do awareness; they do revenue.",
    pull: 'they don\'t do awareness; they do revenue',
    body: [
      "The agency was founded in 2022 by Rohan Patel, who spent four years running growth at a D2C saree brand that scaled from ₹2 crore to ₹28 crore in revenue during his tenure. He knows this specific problem from the inside.",
      "Typical engagement: ₹60,000–90,000/month. Current client list includes five textile brands, two home furnishing companies, and one food brand. Results have been consistent enough to produce a waiting list.",
    ],
    attribution: '— Interviewed Apr 2026 + 3 client references',
    hours: '10:00–19:30',
    phone: '+91 98245 72234',
    address: 'Anand Nagar Road, Satellite',
    details: { 'Min. retainer': '₹60,000/month', Speciality: 'Shopify / D2C / email', Founded: '2022', Team: '6 people' },
    scores: { results: 4.6, communication: 4.5, speed: 4.4, value: 4.5 },
  },
  {
    id: 'pebble-creative',
    rank: '05',
    name: 'Pebble Creative',
    neighborhood: 'Prahlad Nagar',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.7,
    reviews: 78,
    price: 2,
    tags: ['Brand identity', 'Packaging', 'Startups'],
    img: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=900&q=80',
    categorySlug: 'agencies',
    subtitle: 'Branding studio',
    review:
      "Four designers, no account managers, direct access to the people making your work. Pebble Creative is the branding studio Ahmedabad's better startups and premium SMEs come to when they want something that doesn't look like it came from a template.",
    pull: 'direct access to the people making your work',
    body: [
      "Their portfolio is evidence: a craft gin brand, a Patan-based silk weaver selling internationally, two fintech startups, a restaurant group. The work has a visual consistency that suggests a genuine point of view, not just technical competence.",
      "Branding projects start at ₹1.5 lakh for a complete identity system. Packaging design starts at ₹60,000. Turnaround on a full identity project is typically 6–8 weeks, which is fast for this quality level.",
    ],
    attribution: '— Interviewed Mar 2026',
    hours: '10:00–18:30',
    phone: '+91 98242 18844',
    address: 'Prahladnagar Garden Road, Prahlad Nagar',
    details: { 'Identity project': 'From ₹1,50,000', Speciality: 'Brand identity & packaging', Team: '4 senior designers', Turnaround: '6–8 weeks' },
    scores: { results: 4.8, communication: 4.7, speed: 4.3, value: 4.6 },
  },
]

// ─────────────────────────────────────────
// INTERIOR DESIGNERS
// ─────────────────────────────────────────
export const designers: Listing[] = [
  {
    id: 'pol-atelier',
    rank: '01',
    name: 'Pol Atelier',
    neighborhood: 'Old City',
    featured: true,
    verified: true,
    pick: true,
    rating: 4.9,
    reviews: 94,
    price: 3,
    tags: ['Heritage restoration', 'Residential', 'Traditional'],
    img: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&q=80',
    categorySlug: 'designers',
    subtitle: 'Heritage restoration',
    review:
      "Nobody in India knows pol houses better. Pol Atelier has spent twelve years restoring Ahmedabad's old-city havelis — not converting them, restoring them. The distinction matters enormously, and it shows in the work. Their projects have been published in Domus, Architectural Record, and Vogue Living.",
    pull: 'not converting them, restoring them',
    body: [
      "Principal architect Aarav Shah studied at CEPT, then apprenticed under a Japanese restoration firm in Kyoto for three years. He came back with a methodology that treats heritage buildings as living documents: nothing removed that can be repaired, nothing modern introduced that the original builder would find hostile.",
      "Projects take 18 to 36 months. Fees are typically ₹400–800 per sq.ft for restoration work, which sounds expensive until you see what the alternative produces. There are currently three projects on the books. Enquiries welcome; new projects in 2027.",
    ],
    attribution: '— Editorial team · Two site visits',
    hours: '10:00–18:00',
    phone: '+91 79 2213 6688',
    address: 'Teen Darwaza, Old City',
    details: { Speciality: 'Pol house restoration', 'Fee range': '₹400–800/sq.ft', 'Project timeline': '18–36 months', Published: 'Domus, Vogue Living' },
    scores: { portfolio: 5.0, process: 4.8, timeline: 4.2, value: 4.4 },
  },
  {
    id: 'studio-trident',
    rank: '02',
    name: 'Studio Trident',
    neighborhood: 'SG Highway',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.6,
    reviews: 213,
    price: 3,
    tags: ['Commercial', 'Turnkey', 'Restaurants & offices'],
    img: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80',
    categorySlug: 'designers',
    subtitle: 'Commercial & residential',
    review:
      "The go-to for Ahmedabad's serious restaurant fit-outs, office renovations, and premium residential projects. Studio Trident has been responsible for three of the best-looking new restaurants in the city and consistently delivers commercial projects on time — which is an achievement in Ahmedabad's construction environment.",
    pull: 'consistently delivers commercial projects on time',
    body: [
      "Meera and Rohan Vora founded Studio Trident in 2016 after stints at large firms in Mumbai. They brought back a commercial rigour that most Ahmedabad design studios lack — project management systems, contractor relationships, timeline accountability.",
      "Residential projects: ₹1,200–1,800/sq.ft for complete turnkey. Commercial: project-specific quotes. The studio takes on about eight projects per year to maintain quality. Currently booking for Q4 2026.",
    ],
    attribution: '— Editorial team · Portfolio review + client interviews',
    hours: '10:00–19:00',
    phone: '+91 79 4015 7744',
    address: 'Prahladnagar Corporate Road, SG Highway',
    details: { Speciality: 'Commercial & residential', 'Fee range': '₹1,200–1,800/sq.ft', 'Projects/year': '8 max', Portfolio: 'restaurants, offices, villas' },
    scores: { portfolio: 4.7, process: 4.6, timeline: 4.7, value: 4.3 },
  },
  {
    id: 'the-green-room',
    rank: '03',
    name: 'The Green Room',
    neighborhood: 'Vastrapur',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.5,
    reviews: 128,
    price: 2,
    tags: ['Sustainable', 'Natural materials', 'Biophilic'],
    img: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80',
    categorySlug: 'designers',
    subtitle: 'Sustainable design',
    review:
      "The only firm in Ahmedabad that specifies reclaimed teak before Italian marble. The Green Room designs interiors that take seriously both the visual and the environmental, which — in 2026 — should be table stakes. In practice, it still makes them unusual.",
    pull: 'specifies reclaimed teak before Italian marble',
    body: [
      "Designer Priti Joshi sources materials locally where possible (Rajasthani stone, Kutchi textiles, Gujarati brass), specifies reclaimed wood over new for structural elements, and commissions local craftspeople for joinery and upholstery. The results look better than they sound, which is usually the worry with sustainable design.",
      "Projects from ₹800/sq.ft. Consultation includes a materials sustainability audit. Particularly strong on residential bedroom and living spaces. The studio is small — three designers — which means Priti is personally involved on every project.",
    ],
    attribution: '— Editorial team · Portfolio review',
    hours: '10:00–18:00',
    phone: '+91 98247 56611',
    address: 'Vastrapur Lake Side, Vastrapur',
    details: { Speciality: 'Sustainable residential', 'Fee range': 'From ₹800/sq.ft', Materials: 'Reclaimed, local sourcing', Team: '3 designers' },
    scores: { portfolio: 4.6, process: 4.5, timeline: 4.4, value: 4.6 },
  },
  {
    id: 'priya-vora-studio',
    rank: '04',
    name: 'Priya Vora Studio',
    neighborhood: 'Prahlad Nagar',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.7,
    reviews: 71,
    price: 3,
    tags: ['Hospitality', 'Hotels & F&B', 'Luxury'],
    img: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=80',
    categorySlug: 'designers',
    subtitle: 'Hospitality design',
    review:
      "Responsible for three of Ahmedabad's most talked-about restaurant interiors and one boutique hotel in Diu that won a regional design award. Priya Vora Studio specialises in hospitality — the specific discipline of designing spaces that have to work commercially while feeling personal.",
    pull: 'spaces that have to work commercially while feeling personal',
    body: [
      "Priya spent seven years at a hospitality design firm in Singapore before returning. She brought back a rigour about how guests move through a space — sightlines, acoustics, table density, the path from entrance to seat — that most residential designers never develop.",
      "Her minimum project value is ₹40 lakh. She works with hospitality developers and individual restaurateurs with serious projects. Currently booking for early 2027.",
    ],
    attribution: '— Editorial team · Portfolio review + site visits',
    hours: '10:00–18:30',
    phone: '+91 79 4019 2255',
    address: 'Prahladnagar Garden, Prahlad Nagar',
    details: { Speciality: 'Hotels & restaurant interiors', 'Min. project': '₹40,00,000', Founded: '2019', Awards: 'Regional Hospitality Design 2024' },
    scores: { portfolio: 4.8, process: 4.6, timeline: 4.5, value: 4.2 },
  },
  {
    id: 'forms-facades',
    rank: '05',
    name: 'Forms & Façades',
    neighborhood: 'Bodakdev',
    featured: false,
    verified: false,
    pick: false,
    rating: 4.4,
    reviews: 156,
    price: 2,
    tags: ['Minimalist', 'Residential', 'Japandi'],
    img: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=900&q=80',
    categorySlug: 'designers',
    subtitle: 'Minimalist residential',
    review:
      "Less is more, but only if the less is very good. Forms & Façades builds interiors on the principle that the quality of a space comes from material selection and proportion, not decoration. The work is quiet. It will still look good in thirty years.",
    pull: 'it will still look good in thirty years',
    body: [
      "The portfolio is almost entirely residential — apartments, row houses, and two bungalows. The aesthetic is Japanese-Scandinavian: pale timbers, concrete textures, minimal hardware, considered light. They resist trend. This makes them the right choice for buyers who intend to live in a space for a decade or longer.",
      "Fees from ₹900/sq.ft. Project timeline typically 8–12 months for a full apartment. Three designers in the studio; the principals handle client meetings directly.",
    ],
    attribution: '— Editorial team · Portfolio review',
    hours: '10:00–19:00',
    phone: '+91 98244 23399',
    address: 'Iscon Cross Roads, Bodakdev',
    details: { Speciality: 'Minimalist residential', 'Fee range': 'From ₹900/sq.ft', Style: 'Japandi / minimalist', 'Project timeline': '8–12 months' },
    scores: { portfolio: 4.5, process: 4.4, timeline: 4.6, value: 4.4 },
  },
]

// ─────────────────────────────────────────
// DOCTORS & CLINICS
// ─────────────────────────────────────────
export const doctors: Listing[] = [
  {
    id: 'vardaan-clinic',
    rank: '01',
    name: 'Vardaan Family Clinic',
    neighborhood: 'Navrangpura',
    featured: false,
    verified: true,
    pick: true,
    rating: 4.8,
    reviews: 1842,
    price: 2,
    tags: ['General physician', 'Family medicine', 'Same-day'],
    img: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=900&q=80',
    categorySlug: 'doctors',
    subtitle: 'Family medicine',
    review:
      "The last general physician in Ahmedabad who still does house calls — if you've been a patient for more than a year and genuinely can't make it in. Dr. Priya Sharma has been running Vardaan since 2008. The average appointment time is 22 minutes, which in 2026 counts as exceptional.",
    pull: 'the average appointment time is 22 minutes',
    body: [
      "Dr. Sharma trained at B.J. Medical College and did her residency at AIIMS Delhi before returning to Ahmedabad to build what she calls a 'slow medicine' practice — patients seen thoroughly, not efficiently. She capped her list at 800 patients and has been on a waiting list for new patients since 2019.",
      "The clinic's WhatsApp system is the best we've encountered: messages answered within 2 hours during clinic hours, prescriptions via PDF the same day for known patients. If you can get in, keep this doctor.",
    ],
    attribution: '— Riya Shah · Patient for 3 years',
    hours: '9:00–13:00, 16:00–20:00',
    phone: '+91 79 2644 6611',
    address: 'Stadium Circle, Navrangpura',
    details: { Speciality: 'General medicine & family health', Consultation: '₹400', 'Avg wait': '10–15 min', 'New patients': 'Waiting list' },
    scores: { expertise: 4.8, wait: 4.9, bedside: 5.0, facilities: 4.4 },
  },
  {
    id: 'skin-story',
    rank: '02',
    name: 'Skin Story Clinic',
    neighborhood: 'C.G. Road',
    featured: true,
    verified: true,
    pick: false,
    rating: 4.7,
    reviews: 2113,
    price: 3,
    tags: ['Dermatology', 'Laser', 'Acne & pigmentation'],
    img: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=900&q=80',
    categorySlug: 'doctors',
    subtitle: 'Dermatology & aesthetics',
    review:
      "Every CEPT and NID student in Ahmedabad has been here for exam-week breakouts. Dr. Anika Shah treats both medical dermatology and cosmetic skin concerns with equal seriousness — which means she'll tell you when you need a procedure and when you don't. The laser technology is current. The prices are honest.",
    pull: 'she\'ll tell you when you need a procedure and when you don\'t',
    body: [
      "Dr. Shah did her fellowship in aesthetic dermatology in Singapore and came back with a clinical and a cosmetic practice running in parallel. The medical side: acne, psoriasis, eczema, pigmentation disorders. The cosmetic side: laser resurfacing, chemical peels, injectables. The same doctor handles both — an unusual and useful combination.",
      "Consultations are ₹600. Procedures are quoted after assessment. The waiting time for a first appointment is typically 2–3 weeks; established patients can usually get a slot within a week.",
    ],
    attribution: '— Ananya Mehta · Patient, 2 years',
    hours: '10:00–20:00',
    phone: '+91 79 2640 5522',
    address: 'Mithakhali Six Roads, C.G. Road',
    details: { Speciality: 'Medical & cosmetic dermatology', Consultation: '₹600', 'Wait for first appt.': '2–3 weeks', Equipment: 'Q-switched Nd:YAG, Fractional CO₂' },
    scores: { expertise: 4.8, wait: 4.5, bedside: 4.7, facilities: 4.9 },
  },
  {
    id: 'bone-joint',
    rank: '03',
    name: 'The Bone & Joint Centre',
    neighborhood: 'Bodakdev',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.6,
    reviews: 934,
    price: 3,
    tags: ['Orthopaedics', 'Sports medicine', 'Physiotherapy'],
    img: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=900&q=80',
    categorySlug: 'doctors',
    subtitle: 'Orthopaedics & sports medicine',
    review:
      "The only sports orthopaedic clinic in Ahmedabad with a full in-house physiotherapy team. Dr. Vijay Mehta operates on Saturdays and sees outpatients Monday through Friday. The physio team is better than any standalone practice in the city, and works directly with the surgical team.",
    pull: 'the only sports orthopaedic clinic with a full in-house physio team',
    body: [
      "Dr. Mehta trained at St. James's Hospital in Dublin under one of the leading knee reconstruction surgeons in Europe. He returned to Ahmedabad in 2015 and built a practice around sports injuries — ACLs, rotator cuffs, stress fractures — that has become the referral destination for sports medicine in Gujarat.",
      "The physiotherapy team of seven is led by Meena Patel, who has published research on post-ACL rehabilitation protocols. If you need surgery, come here. If you need to avoid it, the physio team will give you the best chance.",
    ],
    attribution: '— Dev Patel · Post-ACL rehab patient',
    hours: '9:00–18:00',
    phone: '+91 79 2685 4400',
    address: 'Judges Bungalow Road, Bodakdev',
    details: { Speciality: 'Orthopaedics & sports medicine', Consultation: '₹800', 'In-house physio': 'Yes, 7 physiotherapists', Surgery: 'Saturday operating days' },
    scores: { expertise: 4.8, wait: 4.3, bedside: 4.5, facilities: 4.8 },
  },
  {
    id: 'smile-studio',
    rank: '04',
    name: 'Smile Studio',
    neighborhood: 'Satellite',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.7,
    reviews: 1521,
    price: 2,
    tags: ['Cosmetic dental', 'Implants', 'Braces & aligners'],
    img: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=900&q=80',
    categorySlug: 'doctors',
    subtitle: 'Dental clinic',
    review:
      "Dr. Mansi Patel trained at AIIMS and returned to Ahmedabad to build a dental practice around a simple principle: do the treatment that's indicated, not the treatment that's profitable. The implant success rate over five years is documented and available on request.",
    pull: 'the treatment that\'s indicated, not the treatment that\'s profitable',
    body: [
      "The technology at Smile Studio is current without being performative: digital X-ray, intraoral scanner, same-day crowns via CAD/CAM. More importantly, Dr. Patel takes 45 minutes for a first consultation, shows you the X-rays, explains the options, and gives you time to think. This is not the norm.",
      "Consultations are ₹300. Implants from ₹25,000 per implant, which is lower than the Bodakdev clinic average. The waiting time for appointments is typically 3–5 days.",
    ],
    attribution: '— Ananya Mehta · Patient, 18 months',
    hours: '9:30–20:00',
    phone: '+91 98255 33411',
    address: 'Shyamal Cross Roads, Satellite',
    details: { Speciality: 'General & cosmetic dentistry', Consultation: '₹300', 'Implant cost': 'From ₹25,000', Technology: 'CAD/CAM same-day crowns' },
    scores: { expertise: 4.9, wait: 4.6, bedside: 4.7, facilities: 4.8 },
  },
  {
    id: 'little-wonders',
    rank: '05',
    name: 'Little Wonders Paediatrics',
    neighborhood: 'Prahlad Nagar',
    featured: false,
    verified: true,
    pick: true,
    rating: 4.9,
    reviews: 3204,
    price: 2,
    tags: ['Paediatrician', 'Vaccines', 'Child-friendly'],
    img: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=900&q=80',
    categorySlug: 'doctors',
    subtitle: 'Paediatric clinic',
    review:
      "The waiting room has a ball pit. The doctor has 22 years of experience and the patience of someone who has explained febrile convulsions to panicked parents ten thousand times. Dr. Hetal Desai is the paediatrician every Ahmedabad parent tries to get on the list for, and the wait is worth it.",
    pull: 'the paediatrician every Ahmedabad parent tries to get',
    body: [
      "Dr. Desai trained at KGMU Lucknow and did a fellowship in neonatal medicine. Her practice covers everything from routine vaccinations to complex developmental assessments. She has a particular reputation for getting to the bottom of recurring infections that other doctors have dismissed.",
      "The clinic WhatsApp is staffed until 10pm for patient families. After-hours emergency advice is available. Consultations ₹500. New patient appointments are typically available within 2 weeks.",
    ],
    attribution: '— Riya Shah · Parent of patient',
    hours: '10:00–20:00',
    phone: '+91 79 4018 7744',
    address: 'Prahladnagar Garden, Prahlad Nagar',
    details: { Speciality: 'General & developmental paediatrics', Consultation: '₹500', 'After-hours WhatsApp': 'Until 22:00', Experience: '22 years' },
    scores: { expertise: 4.9, wait: 4.7, bedside: 5.0, facilities: 4.7 },
  },
]

// ─────────────────────────────────────────
// WEEKEND GETAWAYS
// ─────────────────────────────────────────
export const weekend: Listing[] = [
  {
    id: 'white-rann',
    rank: '01',
    name: 'White Rann of Kutch',
    neighborhood: 'Kutch district',
    featured: true,
    verified: true,
    pick: true,
    rating: 4.9,
    reviews: 8412,
    price: 3,
    tags: ['Sunrise', 'Salt desert', 'Rann Utsav'],
    img: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=900&q=80',
    categorySlug: 'weekend',
    subtitle: 'Salt desert escape',
    review:
      "The largest salt desert in the world turns the colour of mercury at dawn. Come in winter — November to February — when the Rann Utsav runs and the temperatures are survivable. Drive up the night before and sleep at a tent city. The sunrise from the salt flat is something you will attempt to describe for the rest of your life.",
    pull: 'something you will attempt to describe for the rest of your life',
    body: [
      "The drive from Ahmedabad is five to six hours on the NH-41 towards Bhuj. The last hour goes through Kutchi villages and scrubland that is already extraordinary. The white salt flat begins to appear about 20km before Dhordo and nothing really prepares you for the scale of it.",
      "Accommodation options range from basic government guesthouses to premium tent cities with room service and folk performances. The Rann Utsav (November to February) dramatically increases both crowds and quality of facilities. Off-season is quieter and cheaper but the heat is serious — 45°C+ in summer.",
    ],
    attribution: '— Dev Patel · Visited Jan 2026',
    hours: 'Year-round (winter recommended)',
    phone: 'Gujarat Tourism: 1800 233 2244',
    address: 'Dhordo, Kutch — 340km from Ahmedabad',
    details: { Distance: '340km / ~5.5 hours', 'Best time': 'November–February', 'Tent city': '₹5,000–12,000/night', 'Free entry': 'No — Rann Utsav pass required in season' },
    scores: { scenery: 5.0, access: 4.1, stays: 4.5, value: 4.3 },
  },
  {
    id: 'champaner',
    rank: '02',
    name: 'Champaner-Pavagadh',
    neighborhood: 'Panchmahal district',
    featured: false,
    verified: true,
    pick: true,
    rating: 4.8,
    reviews: 3214,
    price: 1,
    tags: ['UNESCO Heritage', 'Trekking', 'Temples'],
    img: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=900&q=80',
    categorySlug: 'weekend',
    subtitle: 'UNESCO World Heritage',
    review:
      "Two hours southeast, at the foot of a volcanic hill, sits one of the best-preserved pre-Mughal Islamic cities in India. Champaner has been a UNESCO World Heritage Site since 2004 and is still not crowded. The mosques, gates, and bastions are extraordinary. Climb Pavagadh hill at dusk.",
    pull: 'still not crowded',
    body: [
      "The Jama Masjid at Champaner is a masterpiece of 15th-century architecture — a fusion of Hindu and Islamic forms that happened because the craftsmen who built it knew both. The sandstone carving is as fine as anything at Fatehpur Sikri. The crowd is a fraction.",
      "The drive takes about 2 hours on NH-64. Stay at one of the heritage homestays near the site — two or three families have opened their old havelis to guests, and they are excellent. Day trip works but the evening light on the ruins justifies a night.",
    ],
    attribution: '— Riya Shah · Visited Feb 2026',
    hours: 'Site open 8:00–18:00',
    phone: 'ASI Gujarat: +91 79 2658 2302',
    address: 'Champaner, Panchmahal — 150km from Ahmedabad',
    details: { Distance: '150km / ~2 hours', 'Best time': 'October–March', 'Entry fee': '₹35 (Indian), ₹550 (foreign)', 'Stay options': 'Heritage homestays ₹1,500–2,500/night' },
    scores: { scenery: 4.9, access: 4.7, stays: 4.2, value: 4.8 },
  },
  {
    id: 'polo-forest',
    rank: '03',
    name: 'Polo Forest',
    neighborhood: 'Sabarkantha district',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.7,
    reviews: 2108,
    price: 1,
    tags: ['Forest', 'Ancient ruins', 'Birding', 'Camping'],
    img: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=900&q=80',
    categorySlug: 'weekend',
    subtitle: 'Forest sanctuary',
    review:
      "Medieval temple ruins overtaken by a teak forest, with a river running through it. Polo Forest is among the least-visited heritage sites in Gujarat — which is a failure of collective imagination, because it is genuinely wonderful. Bring a tent or stay at the forest guesthouse.",
    pull: 'genuinely wonderful',
    body: [
      "The ruins date from the 10th to 15th centuries — a cluster of Jain temples, step wells, and fortifications spread across roughly 4km of forest. The roots of fig trees have grown through the stonework in a way that could be from Angkor Wat. The birding is exceptional: over 275 species recorded.",
      "The drive is about 3.5 hours north of Ahmedabad via Himmatnagar. The forest guesthouse (Gujarat Forest Department) has basic rooms at ₹600/night. Camping is permitted in designated areas. The forest gets busy in winter weekends — arrive Friday night for the best experience.",
    ],
    attribution: '— Ananya Mehta · Visited Dec 2025',
    hours: 'Forest open sunrise to sunset',
    phone: 'Gujarat Forest Dept: +91 2772 240 233',
    address: 'Polo, Sabarkantha — 165km from Ahmedabad',
    details: { Distance: '165km / ~3.5 hours', 'Best time': 'October–February', 'Forest guesthouse': '₹600/night', 'Entry fee': '₹20' },
    scores: { scenery: 4.8, access: 4.3, stays: 4.2, value: 4.7 },
  },
  {
    id: 'rani-ki-vav',
    rank: '04',
    name: 'Rani ki Vav',
    neighborhood: 'Patan',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.9,
    reviews: 5621,
    price: 1,
    tags: ['UNESCO Stepwell', 'Architecture', 'Day trip'],
    img: 'https://images.unsplash.com/photo-1598135753163-6167c1a1ad65?w=900&q=80',
    categorySlug: 'weekend',
    subtitle: 'UNESCO stepwell',
    review:
      "The finest stepwell in India, and one of the most extraordinary pieces of architecture in the world. Rani ki Vav was built in the 11th century, buried by a flood for 700 years, and excavated by the ASI in the 1980s. The carvings on the 500+ sculptures are in near-perfect condition. It is on the ₹100 note for a reason.",
    pull: 'on the ₹100 note for a reason',
    body: [
      "The scale is not apparent from photographs. It is roughly the size of a large cathedral, descending seven storeys below ground, with each level lined by carved columns and panels depicting Vishnu's avatars, apsaras, and geometric patterns of such intricacy that you will repeatedly stop mid-step.",
      "Two hours northwest of Ahmedabad via NH-48. Combine it with a visit to Patan's Patola silk weavers — only a handful of families still practise this double-ikat technique, and one or two welcome visitors. Day trip is entirely feasible; leave by 7am.",
    ],
    attribution: '— Riya Shah · Visited Jan 2026',
    hours: '8:00–18:00 (closed Fridays)',
    phone: 'ASI Patan: +91 2766 220 343',
    address: 'Patan — 125km from Ahmedabad',
    details: { Distance: '125km / ~2 hours', 'Entry fee': '₹40 (Indian), ₹600 (foreign)', 'Best time': 'Year-round (early morning)', 'Also visit': 'Patola weaving workshops' },
    scores: { scenery: 4.9, access: 4.7, stays: 3.6, value: 4.9 },
  },
  {
    id: 'saputara',
    rank: '05',
    name: 'Saputara Hill Station',
    neighborhood: 'Dang district',
    featured: false,
    verified: false,
    pick: false,
    rating: 4.4,
    reviews: 6821,
    price: 2,
    tags: ['Hill station', 'Monsoon', 'Lake', 'Sunrise point'],
    img: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=900&q=80',
    categorySlug: 'weekend',
    subtitle: 'Hill station',
    review:
      "Gujarat's only hill station, which tells you both everything and nothing. In the monsoon (July–September), when the Sahyadri hills are green and the waterfalls are running, Saputara is beautiful. In the summer, it's just less hot than Ahmedabad, which is not the same thing.",
    pull: 'less hot than Ahmedabad, which is not the same thing',
    body: [
      "The drive from Ahmedabad is around 4 hours via Surat on NH-48. The road into the hills from Waghai is genuinely lovely — forest, waterfalls in season, roadside tribal art. Saputara town itself is unremarkable but the surrounding landscape is not.",
      "Stay options have improved significantly since 2022. A couple of boutique resorts have opened in the Dang tribal villages below the plateau, which are better than the standard hill-station hotels in town. Book the village resorts in advance for monsoon weekends — they fill up.",
    ],
    attribution: '— Ananya Mehta · Visited Aug 2025',
    hours: 'Year-round (July–September peak)',
    phone: 'Gujarat Tourism: 1800 233 2244',
    address: 'Saputara, Dang — 230km from Ahmedabad',
    details: { Distance: '230km / ~4 hours', 'Best time': 'July–September (monsoon)', Stay: 'Village resorts ₹3,000–5,000/night', Altitude: '875m above sea level' },
    scores: { scenery: 4.5, access: 4.2, stays: 4.2, value: 4.4 },
  },
  {
    id: 'lothal',
    rank: '06',
    name: 'Lothal',
    neighborhood: 'Bhal region',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.6,
    reviews: 1892,
    price: 1,
    tags: ['Indus Valley', 'Museum', 'History', 'Day trip'],
    img: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=900&q=80',
    categorySlug: 'weekend',
    subtitle: 'Ancient civilisation',
    review:
      "4,500 years ago, this was a port city with the world's first known tidal dock, a sophisticated bead-making industry, and a drainage system better than most Indian cities managed until the 20th century. The Lothal Museum is understated and excellent. Bring a child.",
    pull: 'the world\'s first known tidal dock',
    body: [
      "The excavated site itself is flat and requires imagination — the structures are mostly foundations now, outlined in brick. But the museum next to the site does the heavy lifting: scale models, artefacts, explanations of the drainage systems, the granary, the dockyard. The finds include a game board that looks remarkably similar to ludo.",
      "About 80km southwest of Ahmedabad, roughly 90 minutes. Easy half-day trip. Combine with the Nalsarovar Bird Sanctuary (20km away) for a full day. The museum is run by the ASI and entry is ₹30 for Indians.",
    ],
    attribution: '— Dev Patel · Visited Feb 2026',
    hours: 'Museum 10:00–17:00 (closed Fridays)',
    phone: 'ASI: +91 2714 228 100',
    address: 'Lothal, Dholka taluka — 80km from Ahmedabad',
    details: { Distance: '80km / ~1.5 hours', 'Entry fee': '₹30 (Indian)', 'Museum quality': 'Excellent', 'Also visit': 'Nalsarovar Bird Sanctuary (20km away)' },
    scores: { scenery: 4.2, access: 4.5, stays: 3.5, value: 4.9 },
  },
]

// ─────────────────────────────────────────
// EVENTS THIS MONTH
// ─────────────────────────────────────────
export const events: Listing[] = [
  {
    id: 'saptak-2026',
    rank: '01',
    name: 'Saptak Annual Music Festival',
    neighborhood: 'Tagore Hall · Shahibaug',
    featured: true,
    verified: true,
    pick: true,
    rating: 4.9,
    reviews: 4120,
    price: 2,
    tags: ['Classical music', 'Annual', 'Multi-day'],
    img: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=900&q=80',
    categorySlug: 'events',
    subtitle: 'Classical music festival',
    review:
      "India's finest classical music festival, run entirely on merit and without corporate interference since 1980. Eight nights of Hindustani and Carnatic performances, beginning at 6pm and running until well after midnight. The audience is extraordinary — people who know the music and stay for all of it.",
    pull: 'the audience is extraordinary',
    body: [
      "Saptak was founded by sitarist Part Hariprasad Chaurasia, Hariprasad Chaurasia — actually it was founded by a group of musicians who wanted to give Ahmedabad the classical music festival it deserved. Over forty-five years, it has grown into an event that every serious musician in India wants to play.",
      "Tickets (₹800–2,500 per evening) go on sale in October. The premium seats near the stage sell out in hours. General admission is available at the door and is entirely adequate — the acoustics at Tagore Hall are excellent from anywhere in the room.",
    ],
    attribution: '— Ananya Mehta · Attended 2025 & 2026 editions',
    hours: '18:00–01:00 daily (8 nights)',
    phone: '+91 79 2657 5577',
    address: 'Tagore Hall, Shahibaug',
    details: { Duration: '8 evenings', Tickets: '₹800–2,500 per evening', When: 'First week of January annually', 'Last edition': 'Jan 2026' },
    scores: { vibe: 5.0, crowd: 4.8, venue: 4.6, value: 4.7 },
  },
  {
    id: 'design-week-2026',
    rank: '02',
    name: 'Design Week Ahmedabad',
    neighborhood: 'CEPT Campus · Navrangpura',
    featured: false,
    verified: true,
    pick: true,
    rating: 4.7,
    reviews: 892,
    price: 1,
    tags: ['Design', 'Architecture', 'Talks & exhibition'],
    img: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=900&q=80',
    categorySlug: 'events',
    subtitle: 'Design & architecture festival',
    review:
      "CEPT University opens its campus for five days of talks, installations, and exhibitions. Architects, designers, and planners from across India gather in a city that was designed by Le Corbusier and Louis Kahn — a context that gives every conversation about the built environment a certain urgency.",
    pull: 'a city that was designed by Le Corbusier and Louis Kahn',
    body: [
      "The programme runs from morning seminars to late-evening installations. The day talks cover architecture, urban design, graphic design, and craft — often in the same afternoon. The evening events are more social: studio tours, rooftop gatherings, film screenings.",
      "Entry to the campus is free; individual events require registration. The campus itself — with its Doshi-designed stepped gardens and Kahn-influenced faculty buildings — is worth visiting regardless of the programme.",
    ],
    attribution: '— Riya Shah · Attended 2025 edition',
    hours: '9:00–22:00 daily (5 days)',
    phone: '+91 79 2630 2470',
    address: 'CEPT University, Navrangpura',
    details: { Duration: '5 days', Tickets: 'Free entry / event registration', When: 'May 15–19, 2026', Venue: 'CEPT Campus' },
    scores: { vibe: 4.8, crowd: 4.7, venue: 4.9, value: 4.7 },
  },
  {
    id: 'lit-fest-2026',
    rank: '03',
    name: 'Ahmedabad Literature Festival',
    neighborhood: 'Shreyas Sankul · Paldi',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.6,
    reviews: 1240,
    price: 1,
    tags: ['Books', 'Authors', 'Panel discussions'],
    img: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=900&q=80',
    categorySlug: 'events',
    subtitle: 'Literary festival',
    review:
      "Less corporate than Jaipur, more intimate than Delhi, and taking place in a city with a genuine literary culture in three languages: Gujarati, Hindi, English. The Ahmedabad Lit Fest hosts 60 to 80 speakers across three days in a restored heritage compound. The Gujarati sessions are the best-attended.",
    pull: 'a city with a genuine literary culture in three languages',
    body: [
      "Now in its seventh year, the festival has found its audience: readers who come for the conversations rather than the celebrity authors. The programming is genuinely diverse — novelists, poets, historians, scientists, filmmakers — and the discussions go places that more polished festivals don't allow.",
      "Passes: ₹500 for the full three days, which includes all sessions and the book fair. Day passes ₹200. Most speakers sign books in the evening and are accessible in a way that Jaipur has made impossible.",
    ],
    attribution: '— Ananya Mehta · Attended 2025 edition',
    hours: '9:00–21:00 daily (3 days)',
    phone: '+91 98240 63311',
    address: 'Shreyas Sankul, Paldi',
    details: { Duration: '3 days', 'Full pass': '₹500', When: 'May 22–24, 2026', Languages: 'Gujarati, Hindi, English' },
    scores: { vibe: 4.7, crowd: 4.6, venue: 4.5, value: 4.7 },
  },
  {
    id: 'garba-by-the-lake',
    rank: '04',
    name: 'Garba by the Lake',
    neighborhood: 'Vastrapur Lake',
    featured: false,
    verified: true,
    pick: false,
    rating: 4.5,
    reviews: 3820,
    price: 1,
    tags: ['Garba', 'Free entry', 'Community'],
    img: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=900&q=80',
    categorySlug: 'events',
    subtitle: 'Community garba night',
    review:
      "A community garba practice that runs on Friday evenings through May and June, building toward Navratri. Organised by local neighbourhood societies with no commercial backing, no ticket sales, and no Instagram filters. Just people dancing around the lake the way they have for generations.",
    pull: 'no Instagram filters',
    body: [
      "Organised by the Vastrapur Residents Association since 2019. The event uses traditional folk music — dhol, shehnai, tabla — rather than the Bollywood remixes that dominate commercial garba venues. The dance circles form naturally and newcomers are welcomed without ceremony.",
      "Free entry. Bring your own water. The event begins at 20:00 and runs until midnight or whenever the dhol player's arms give out, whichever comes first.",
    ],
    attribution: '— Dev Patel · Regular attendee',
    hours: 'Fridays 20:00–midnight',
    phone: 'Vastrapur RA: +91 98250 12233',
    address: 'Vastrapur Lake Garden',
    details: { Entry: 'Free', Music: 'Live folk — dhol & shehnai', When: 'Every Friday, May–June', 'Dress code': 'Traditional or casual' },
    scores: { vibe: 4.6, crowd: 4.5, venue: 4.7, value: 5.0 },
  },
  {
    id: 'sufi-night-sangath',
    rank: '05',
    name: 'Sufi Night at Sangath',
    neighborhood: "B.V. Doshi's Studio · Thaltej",
    featured: false,
    verified: true,
    pick: false,
    rating: 4.8,
    reviews: 612,
    price: 2,
    tags: ['Sufi music', 'Heritage venue', 'Intimate'],
    img: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=900&q=80',
    categorySlug: 'events',
    subtitle: 'Sufi music concert',
    review:
      "An evening of Sufi qawwali at the studio compound of the late Pritzker Prize-winning architect B.V. Doshi — a setting that makes every other concert venue in Ahmedabad feel slightly inadequate. 80 seats, no standing room, no exceptions. Worth every effort to get a ticket.",
    pull: 'makes every other concert venue feel slightly inadequate',
    body: [
      "The Sangath studio was Doshi's personal workspace and experimental architecture laboratory. The vaulted concrete forms create acoustics that suit the human voice in a way no purpose-built concert hall achieves. The qawwali tradition demands intimacy and Sangath delivers it.",
      "Tickets (₹600) sell through the studio website and sell out within 24 hours of going on sale. The guest musician for the May edition is Madan Gopal Singh. Doors open at 18:30; programme begins at 19:00.",
    ],
    attribution: '— Riya Shah · Attended Mar 2026',
    hours: '19:00–22:30',
    phone: '+91 79 2685 2122',
    address: "Sangath Studio, B.V. Doshi Campus, Thaltej",
    details: { Tickets: '₹600', Capacity: '80 seats only', When: 'Sat 9 May 2026', 'Book via': 'sangath-events.in' },
    scores: { vibe: 4.9, crowd: 4.8, venue: 5.0, value: 4.6 },
  },
]

// ─────────────────────────────────────────
// MAP + HELPERS
// ─────────────────────────────────────────
export const listingsByCategory: Record<string, Listing[]> = {
  cafes,
  restaurants,
  coworking,
  gyms,
  agencies,
  designers,
  doctors,
  weekend,
  events,
}

export const allListings: Listing[] = Object.values(listingsByCategory)
  .flat()
  .filter((l, i, arr) => arr.findIndex((x) => x.id === l.id) === i)

export function getListingAndCategory(id: string): { listing: Listing; categorySlug: string } | null {
  for (const [slug, listings] of Object.entries(listingsByCategory)) {
    const listing = listings.find((l) => l.id === id)
    if (listing) return { listing, categorySlug: slug }
  }
  return null
}

// ─────────────────────────────────────────
// CALENDAR EVENTS (homepage strip)
// ─────────────────────────────────────────
export const calendarEvents = [
  {
    date: 'Fri 09',
    time: '19:00',
    title: 'Sufi night at Sangath, with Madan Gopal Singh',
    location: "B.V. Doshi's studio · Thaltej",
    price: '₹600',
  },
  {
    date: 'Thu 15',
    time: '09:00',
    title: 'Design Week Ahmedabad opens — CEPT campus',
    location: 'CEPT University · Navrangpura',
    price: 'Free',
  },
  {
    date: 'Fri 16',
    time: '20:00',
    title: 'Garba by the Lake — community session',
    location: 'Vastrapur Lake Garden',
    price: 'Free',
  },
  {
    date: 'Thu 22',
    time: '09:00',
    title: 'Ahmedabad Literature Festival opens',
    location: 'Shreyas Sankul · Paldi',
    price: '₹200/day',
  },
  {
    date: 'Fri 23',
    time: '20:00',
    title: 'Comedy showcase: Aakash Mehta & friends',
    location: 'The Comedy Theatre · Bodakdev',
    price: '₹499',
  },
  {
    date: 'Sat 24',
    time: '06:30',
    title: 'Heritage walk through the pols of Khadia',
    location: 'Starts at Swaminarayan Temple',
    price: '₹150',
  },
  {
    date: 'Sat 31',
    time: '17:30',
    title: 'Garba by the Lake — closing session of May',
    location: 'Vastrapur Lake Garden',
    price: 'Free',
  },
]

export function getCategoryMeta(slug: string) {
  const deks: Record<string, string> = {
    cafes:
      "We drank a lot of coffee. We sat in a lot of chairs. Most cafés in Ahmedabad are mediocre — these six are not. Ranked by what we'd actually go back to, not by who pays us. (Nobody does.)",
    restaurants:
      'Ahmedabad is one of the great vegetarian food cities in the world. It also has some quietly excellent non-veg. We rank both, honestly — and we never accept a free meal.',
    coworking:
      'Hot desks, private offices, heritage havelis — we tested the internet in all of them. Most coworking spaces in Ahmedabad overpromise on vibes and underdeliver on broadband. These ones actually work.',
    gyms:
      'Finding a gym in Ahmedabad is easy. Finding one with good equipment, decent coaching, and no gym-bro ego at the door — that takes research. This is our shortlist.',
    agencies:
      'A good digital marketing agency in Ahmedabad can triple your revenue. A bad one will burn your budget and ghost your calls. We called them all, checked client references, and ranked what we found.',
    designers:
      'Interior design in Ahmedabad ranges from pol-house restoration masters to Instagram-aesthetic studios with no substance. We rank only the former — and anyone else who genuinely knows what they are doing.',
    doctors:
      'The best doctors in Ahmedabad are not always the most Googled. We talked to patients, checked credentials, and visited clinics. Here is who we trust.',
    weekend:
      'Rann of Kutch, Champaner, Rani ki Vav, Polo Forest. Within four hours of Ahmedabad, some of the best travel in India. We have ranked the drives, stays, and timings.',
    events:
      "What's happening in Ahmedabad this month that's actually worth your evening. We skip the mall inaugurations and list the ones we'd go to ourselves.",
  }
  return deks[slug] || deks.cafes
}
